spring:
  thymeleaf:
    mode: HTML
#    mode: LEGACYHTML5
  profiles:
    active: dev
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png

pagehelper:
  # 指定数据库，可以不配置，pagehelper插件会自动检测数据库的类型。
  helper-dialect: mysql
  # 分页合理化参数默认false，当该参数设置为true 时，pageNum <= 0 时，默认显示第一页，pageNum 超过 pageSize 时，显示最后一页。
  reasonable: true
  # 用于从对象中根据属性名取值，可以配置pageNum，pageSize，count 不用配置映射的默认值。
  support-methods-arguments: true
  # 分页插件会根据查询方法的参数中，自动根据params 配置的字段中取值，找到合适的值会自动分页。　
  params: count=countsql

